"""Export a policy into Guardrails AI: a custom Validator wrapping this runtime.

Verified against their current docs: a Guard composes validators via `Guard().use(...)`,
custom validators register by string name with `@register_validator`, and every
validator of a Guard runs unconditionally against the same value — no ordering, no
conditional execution. So, as with LiteLLM, the honest export compiles the whole policy
into ONE validator that runs `GuardrailRouter` internally: staged execution, early
exits and fail-closed error semantics all behave as measured, inside a framework that
could not express them natively.
"""

from collections.abc import Mapping
from dataclasses import dataclass

from guardopt.domain.inputs import GuardrailDefinition
from guardopt.domain.policy import Policy
from guardopt.integrations.common import (
    definitions_literal,
    require_definitions_for,
    safe_for_generated_source,
)

__all__ = ["GuardrailsAIExport", "export_guardrails_ai"]

_MODULE_TEMPLATE = '''\
"""guardopt policy '{policy_name}' as a Guardrails AI custom validator.

Generated by guardopt.integrations.export_guardrails_ai. The embedded policy is
the exact measured artifact; verdicts come from guardopt's own runtime router.
Implement `build_guards()` (your scorers) before use.
"""

from typing import Any, Dict

from guardrails.validators import (
    FailResult,
    PassResult,
    ValidationResult,
    Validator,
    register_validator,
)

from guardopt import GuardrailDefinition, Policy, PolicyOutcome, ScoreDirection
from guardopt.runtime.router import GuardrailRouter

POLICY_JSON = r"""
{policy_json}
"""

DEFINITIONS: dict[str, GuardrailDefinition] = {definitions}


def build_guards():
    """Return the scorers this policy names: objects with a `name` and an
    `evaluate(request) -> GuardrailReading`. See guardopt.runtime.protocol."""
    raise NotImplementedError(
        "wire your scorers here; the policy needs: {guard_names}"
    )


@register_validator(name="{validator_name}", data_type="string")
class GuardoptPolicy(Validator):
    def __init__(self, on_fail=None, **kwargs):
        super().__init__(on_fail=on_fail, **kwargs)
        self.router = GuardrailRouter(
            guards=build_guards(),
            policy=Policy.from_json(POLICY_JSON),
            definitions=DEFINITIONS,
        )

    def _validate(self, value: Any, metadata: Dict) -> ValidationResult:
        decision = self.router.run_sync({{"text": str(value)}})
        if decision.outcome is PolicyOutcome.FAIL:
            fired = ", ".join(
                name for name, outcome in decision.outcomes if outcome.value == "fail"
            )
            return FailResult(
                error_message=(
                    f"blocked by guardopt policy '{{decision.policy_name}}'"
                    f" (fired: {{fired}})"
                )
            )
        return PassResult()
'''

_USAGE_TEMPLATE = """\
# After placing the module on your import path and implementing build_guards():
from guardrails import Guard, OnFailAction

from {module_name} import GuardoptPolicy

guard = Guard().use(GuardoptPolicy(on_fail=OnFailAction.EXCEPTION))
guard.validate("the text to check")
"""


@dataclass(frozen=True, slots=True)
class GuardrailsAIExport:
    validator_module: str
    usage_snippet: str
    module_name: str
    notes: tuple[str, ...]


def export_guardrails_ai(
    policy: Policy,
    definitions: Mapping[str, GuardrailDefinition],
    *,
    validator_name: str = "guardopt-policy",
    module_name: str = "guardopt_validator",
) -> GuardrailsAIExport:
    """The policy as one Guardrails AI validator, behaviour-preserving by construction."""
    require_definitions_for(policy, definitions)

    # Names are sanitised before templating — interpolated raw into the generated module's
    # docstring / string literals, a crafted name would break out and inject code that runs
    # when the caller imports the module. `policy.to_json()` and `definitions_literal` (via
    # `!r`) are already safe.
    module = _MODULE_TEMPLATE.format(
        policy_name=safe_for_generated_source(policy.name),
        policy_json=policy.to_json(),
        definitions=definitions_literal(policy, definitions),
        guard_names=safe_for_generated_source(", ".join(policy.enabled_names)),
        validator_name=safe_for_generated_source(validator_name),
    )
    notes = [
        "build_guards() is deliberately unimplemented: wire your scorers, then run "
        "one request end to end before trusting the deployment.",
        "The validator fails on FAIL only; WARNING outcomes return PassResult — "
        "Guardrails AI has no warning tier. Route review-queue traffic off your own "
        "logging around the router if you need it.",
        "The validator runs the router synchronously (Guardrails AI validators are "
        "sync); a cascade still skips the stages an early exit saves.",
    ]
    return GuardrailsAIExport(
        validator_module=module,
        usage_snippet=_USAGE_TEMPLATE.format(module_name=module_name),
        module_name=module_name,
        notes=tuple(notes),
    )
