"""Export a policy into a LiteLLM proxy: a CustomGuardrail wrapping this runtime.

Verified against the LiteLLM docs (proxy/guardrails/quick_start and custom_guardrail),
and then against a LIVE proxy (litellm 1.96.0, 2026-08-10): the proxy's `guardrails:`
config lists entries whose `litellm_params.guardrail` may reference a local
`[python_filename].[ClassName]`, and a `CustomGuardrail` subclass receives extra
`litellm_params` keys through `**kwargs`. The live run is what settled the block
mechanism: raising `fastapi.HTTPException(status_code=400)` surfaces to the caller as a
clean 400, where a plain exception became a 500. LiteLLM itself offers only lifecycle
phases (pre/during/post call) — no ordering, no conditional stages — so a cascade is
exported by compiling the WHOLE policy into one custom guardrail that runs
`GuardrailRouter` internally: the deployed verdicts are the router's, which are provably
the optimiser's, whatever the policy's shape. `tests/test_litellm_live.py` re-verifies
the interface against whatever LiteLLM version is installed.

The emitted module embeds the policy JSON verbatim and the definitions as literals. The
one thing it cannot embed is the user's scorers — `build_guards()` raises with
instructions until they wire their own, which is a hole a reviewer can see rather than
a guess nobody can.
"""

from collections.abc import Mapping
from dataclasses import dataclass

from guardopt.domain.inputs import GuardrailDefinition
from guardopt.domain.policy import Policy
from guardopt.integrations.common import definitions_literal, require_definitions_for

__all__ = ["LiteLLMExport", "export_litellm"]

_VALID_MODES = ("pre_call", "during_call", "post_call")

_CONFIG_TEMPLATE = """\
# guardopt export — add under the top-level `guardrails:` of your LiteLLM proxy
# config.yaml. The referenced module file must sit next to the proxy.
guardrails:
  - guardrail_name: {guardrail_name}
    litellm_params:
      guardrail: {module_name}.GuardoptGuardrail
      mode: "{mode}"
      default_on: true
"""

_MODULE_TEMPLATE = '''\
"""guardopt policy '{policy_name}', compiled into a LiteLLM CustomGuardrail.

Generated by guardopt.integrations.export_litellm. The policy below is embedded
verbatim — the exact artifact that was measured — and the verdict logic is
guardopt's own runtime router, so what this guardrail enforces is what the
optimiser reported, staged execution and fail-closed error handling included.

One assembly step is yours: `build_guards()` must return the scorer objects the
policy names. They are your services; no export can know how to call them.
"""

from litellm.integrations.custom_guardrail import CustomGuardrail

try:
    # The proxy always has fastapi; an HTTPException surfaces a block as a clean 400.
    from fastapi import HTTPException
except ImportError:  # outside the proxy a plain exception still blocks
    HTTPException = None

from guardopt import GuardrailDefinition, Policy, PolicyOutcome, ScoreDirection
from guardopt.runtime.router import GuardrailRouter

POLICY_JSON = r"""
{policy_json}
"""

DEFINITIONS: dict[str, GuardrailDefinition] = {definitions}


def build_guards():
    """Return the guardrail scorers this policy names: objects with a `name` and an
    `evaluate(request) -> GuardrailReading`. See guardopt.runtime.protocol — the
    HttpJsonGuardrail adapter covers the common HTTP case."""
    raise NotImplementedError(
        "wire your scorers here; the policy needs: {guard_names}"
    )


class GuardoptGuardrail(CustomGuardrail):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.router = GuardrailRouter(
            guards=build_guards(),
            policy=Policy.from_json(POLICY_JSON),
            definitions=DEFINITIONS,
        )

    async def _decide(self, text):
        decision = await self.router.run({{"text": text}})
        if decision.outcome is PolicyOutcome.FAIL:
            message = (
                f"blocked by guardopt policy "
                f"'{{decision.policy_name}}': {{decision.reason}}"
            )
            # Verified against a live proxy: a plain exception surfaces as HTTP 500,
            # an HTTPException as the 400 a blocked request deserves.
            if HTTPException is not None:
                raise HTTPException(status_code=400, detail={{"error": message}})
            raise ValueError(message)

__HOOK__
'''

_PROMPT_TEXT_SNIPPET = '''\
        messages = data.get("messages") or []
        text = " ".join(
            str(message.get("content", ""))
            for message in messages
            if isinstance(message, dict)
        )
'''

#: One hook per lifecycle phase, matching the installed CustomGuardrail signatures
#: (verified live by tests/test_litellm_live.py). pre_call and during_call scan the
#: request; post_call scans the model's RESPONSE — the output-guardrail case.
_HOOKS = {
    "pre_call": (
        "    async def async_pre_call_hook(self, user_api_key_dict, cache, data, "
        "call_type):\n"
        + _PROMPT_TEXT_SNIPPET
        + "        await self._decide(text)\n"
        + "        return data\n"
    ),
    "during_call": (
        "    async def async_moderation_hook(self, data, user_api_key_dict, "
        "call_type):\n"
        + _PROMPT_TEXT_SNIPPET
        + "        await self._decide(text)\n"
        + "        return data\n"
    ),
    "post_call": (
        "    async def async_post_call_success_hook(self, data, user_api_key_dict, "
        "response):\n"
        "        parts = []\n"
        "        for choice in getattr(response, \"choices\", None) or []:\n"
        "            message = getattr(choice, \"message\", None)\n"
        "            content = getattr(message, \"content\", None)\n"
        "            if content:\n"
        "                parts.append(str(content))\n"
        "        await self._decide(\" \".join(parts))\n"
        "        return response\n"
    ),
}


@dataclass(frozen=True, slots=True)
class LiteLLMExport:
    """Two files and the caveats. Write `guardrail_module` as `<module_name>.py` next
    to the proxy, merge `config_yaml` into config.yaml, then implement build_guards()."""

    config_yaml: str
    guardrail_module: str
    module_name: str
    notes: tuple[str, ...]


def export_litellm(
    policy: Policy,
    definitions: Mapping[str, GuardrailDefinition],
    *,
    guardrail_name: str = "guardopt-policy",
    module_name: str = "guardopt_guardrail",
    mode: str = "pre_call",
) -> LiteLLMExport:
    """The policy as a LiteLLM custom guardrail, behaviour-preserving by construction."""
    if mode not in _VALID_MODES:
        raise ValueError(f"mode must be one of {_VALID_MODES}, got {mode!r}")
    require_definitions_for(policy, definitions)

    guard_names = ", ".join(policy.enabled_names)
    module = _MODULE_TEMPLATE.format(
        policy_name=policy.name,
        policy_json=policy.to_json(),
        definitions=definitions_literal(policy, definitions),
        guard_names=guard_names,
    ).replace("__HOOK__", _HOOKS[mode])
    config = _CONFIG_TEMPLATE.format(
        guardrail_name=guardrail_name, module_name=module_name, mode=mode
    )

    notes = [
        "build_guards() is deliberately unimplemented: wire your scorers, then run "
        "one request end to end before trusting the deployment.",
        "The guardrail blocks on FAIL only. WARNING outcomes pass through — LiteLLM "
        "has no warning tier — so flagged-for-review traffic must be read off your "
        "own logging around the router if you need it.",
    ]
    if mode == "post_call":
        notes.append(
            "post_call scans the model's RESPONSE, not the prompt: the policy's "
            "thresholds were tuned on whatever text its matrix scored, so use a "
            "matrix of responses when optimising a response-side policy."
        )
    if len(policy.stages) > 1:
        notes.append(
            "The cascade executes inside this one guardrail via guardopt's router "
            "(LiteLLM itself cannot express stages), so early-exit savings and "
            "fail-closed error semantics are preserved as measured."
        )
    return LiteLLMExport(
        config_yaml=config,
        guardrail_module=module,
        module_name=module_name,
        notes=tuple(notes),
    )
