"""Simulated policy in, Sentinel policy body out.

One function does the whole translation, so there is exactly one place to change when the
API moves. Everything it does is a copy: thresholds come through byte-identical, guardrail
names are passed exactly as supplied, and nothing is normalised, rounded or inferred.

**Creating a policy deploys nothing.** Deployment is a separate endpoint
(`POST /policies/{nameOrId}/versions/{version}/deploy`) which this codebase never calls
and has no method for. That is the safety property, and it is asserted by searching the
package for the deploy path rather than by asserting a field.

**No optimiser metadata enters the policy body.** Profile, explanation, simulated metrics and
selection reasoning live on the enclosing recommendation. What goes here is only what
Sentinel stores — asserted as an exact key set, so a future field cannot slip in unnoticed.
"""

import re
from collections.abc import Mapping, Sequence

from guardopt.domain.inputs import GuardrailDefinition
from guardopt.domain.simulation import PolicyCandidate
from guardopt.domain.types import RecommendationProfile, ScoreDirection
from guardopt.domain.warning_bands import silent_warning_threshold
from guardopt.sentinel.schema import (
    DEFAULT_VERSION,
    SentinelGuardrailBinding,
    SentinelPolicy,
    SentinelThresholds,
)

__all__ = [
    "DEFAULT_VERSION",
    "UnmappableWarningBandError",
    "guardrails_given_a_silent_band",
    "policy_description_for",
    "policy_name_for",
    "slugify",
    "to_sentinel_policy",
]

_PROFILE_LABELS: dict[RecommendationProfile, str] = {
    RecommendationProfile.MINIMAL: "Minimal",
    RecommendationProfile.BALANCED: "Balanced",
    RecommendationProfile.STRICT: "Strict",
}

_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


def slugify(text: str) -> str:
    """Lowercase, hyphen-separated, alphanumeric only.

    **A policy name is a URL path segment**, not a label: the deploy endpoint takes
    `:policyNameOrId` in the path and `/check` takes the name in its body. A name
    containing spaces or parentheses — which the first cut of `policy_name_for` produced —
    would need escaping to be addressable, and would not round-trip cleanly. The observed
    upstream example (`example-hateful-policy`) is exactly this shape.
    """
    return _SLUG_STRIP.sub("-", text.lower()).strip("-")


def policy_name_for(profile: RecommendationProfile, system_name: str | None = None) -> str:
    """A URL-safe name that says which profile it is and that it is not live.

    "draft" is in the name, not only in the description, because a policy list in another
    tool may show names and nothing else — and because nothing in the API marks a
    created-but-undeployed policy as such.
    """
    parts = [system_name, _PROFILE_LABELS[profile], "guardrail policy", "draft"]
    return slugify("-".join(part for part in parts if part))


def policy_description_for(
    profile: RecommendationProfile, case_count: int | None = None
) -> str:
    """States the provenance and the status, in that order. Human-readable; the only
    place the profile is named in prose."""
    label = _PROFILE_LABELS[profile]
    measured = (
        f" simulated over {case_count} labelled test cases"
        if case_count is not None
        else " simulated"
    )
    return (
        f"{label} profile, generated by guardopt and{measured}. "
        f"This is a draft: it is not deployed, and the simulated results describe that "
        f"dataset rather than production traffic."
    )


def guardrails_given_a_silent_band(candidate: PolicyCandidate) -> tuple[str, ...]:
    """The guardrails whose warning threshold Sentinel forces us to invent.

    A guardrail the optimiser left bandless is exactly one that `to_sentinel_policy` will
    fit a silent band to, so this needs no scores and no second derivation — it reads the
    candidate.

    Exists so a caller can say so out loud. The explanation is built in the pure domain,
    which does not know Sentinel exists and must not learn; the service composes the two
    and is where the caveat belongs.
    """
    return tuple(name for name, thresholds in candidate.entries if thresholds.warning is None)


class PolicyNotExpressibleError(ValueError):
    """This simulated policy has no faithful Sentinel representation.

    Always raised rather than worked around. The alternatives are to emit a body Sentinel
    rejects, or to emit one it accepts that behaves differently from what was measured —
    and the second is worse, because it looks like it worked.
    """


class UnmappableWarningBandError(PolicyNotExpressibleError):
    """A guardrail blocks but cannot be given a warning band Sentinel will accept.

    Both workarounds are wrong: omitting the field earns a 500, and `warning == failed`
    earns a 400. Guessing a band would make the policy warn on cases the simulation said
    would pass.
    """


class ScoreDirectionNotExpressibleError(PolicyNotExpressibleError):
    """A `LOWER_IS_RISKIER` guardrail cannot go in a Sentinel policy.

    Sentinel requires `warning < failed` for every binding. That encodes an assumption
    that a higher score is riskier — which matches the published documentation, where
    every guardrail scores 0.0-1.0 with higher meaning riskier. A guardrail whose *low*
    scores are the dangerous ones needs `warning > failed` to mean anything, and Sentinel
    will not store that.

    **This is inferred from one error message, not tested against a real lower-is-riskier
    guardrail** — the live catalogue does not appear to contain one. If that changes, this
    is the first thing to re-check. Refusing is still right in the meantime: the only
    other option is to send a body we have good reason to think will be rejected.
    """


def to_sentinel_policy(
    profile: RecommendationProfile,
    candidate: PolicyCandidate,
    definitions: Mapping[str, GuardrailDefinition],
    *,
    observed_scores: Mapping[str, Sequence[float | None]] | None = None,
    system_name: str | None = None,
    case_count: int | None = None,
    name: str | None = None,
    description: str | None = None,
    version: str = DEFAULT_VERSION,
) -> SentinelPolicy:
    """Translate one simulated policy into a Sentinel policy body.

    Raises `KeyError` if the candidate names a guardrail with no definition. That is a
    programming error in the caller, and emitting a partial policy instead would produce
    a body quietly missing a guardrail somebody expected to be there.

    `is_mandatory` and `parameters` are deliberately NOT sent: the real create body has no
    such fields. They stay on `GuardrailDefinition`, where the search needs them.

    **Every binding is given a warning threshold, because Sentinel requires one.** Verified
    live on staging (2026-07-29): omitting `warning` returns a 500, and `warning == failed`
    returns a 400 saying it must be strictly less. So "blocks but never warns" — an
    ordinary result of the profile ladder, and Strict's normal state — has no direct
    representation, and this is the layer that has to resolve that.

    It is resolved with a **silent band** derived from `observed_scores`: the widest band
    no measured score falls into, so the policy Sentinel stores behaves on this dataset
    exactly as the one that was simulated and shown. That keeps the reported numbers
    honest, which inventing a band would not.

    This lives here and not in `domain/warning_bands.py` on purpose. The domain does not
    know Sentinel exists and must not be reshaped by its constraints; the primitive it
    exposes (`silent_warning_threshold`) is a plain fact about scores. Choosing to APPLY
    it is a Sentinel decision, so it is made in the Sentinel layer.
    """
    bindings: list[SentinelGuardrailBinding] = []

    for guardrail_name, thresholds in candidate.entries:
        # Looked up rather than trusted, so an unknown guardrail raises here instead of
        # producing a body that references something the caller never defined.
        definition = definitions[guardrail_name]

        # Checked before the band work, because no band can rescue this one: Sentinel's
        # `warning < failed` rule is incompatible with a guardrail whose low scores are
        # the risky ones, whatever thresholds we pick.
        if definition.score_direction is not ScoreDirection.HIGHER_IS_RISKIER:
            raise ScoreDirectionNotExpressibleError(
                f"guardrail '{guardrail_name}' is {definition.score_direction.value}, and "
                f"a Sentinel policy requires warning < failed on every binding — which "
                f"only makes sense when a higher score is riskier. This policy cannot be "
                f"created in Sentinel as measured."
            )

        warning = thresholds.warning

        if warning is None:
            scores = (observed_scores or {}).get(guardrail_name)
            if scores is None:
                raise UnmappableWarningBandError(
                    f"guardrail '{guardrail_name}' has no warning band, and no observed "
                    f"scores were supplied to derive one from. Sentinel rejects a "
                    f"binding without a warning threshold, so pass observed_scores."
                )
            warning = silent_warning_threshold(definition, thresholds.failed, scores)
            if warning is None:
                raise UnmappableWarningBandError(
                    f"guardrail '{guardrail_name}' blocks at {thresholds.failed}, and no "
                    f"warning threshold strictly below it leaves the measured outcomes "
                    f"unchanged. Sentinel requires warning < failed, so this policy "
                    f"cannot be expressed without altering what was simulated."
                )

        bindings.append(
            SentinelGuardrailBinding(
                name=definition.name,
                thresholds=SentinelThresholds(failed=thresholds.failed, warning=warning),
            )
        )

    return SentinelPolicy(
        name=name or policy_name_for(profile, system_name),
        description=description or policy_description_for(profile, case_count),
        version=version,
        guardrails=bindings,
    )
